### ISSUE TITLE
Is this actively maintained?

### ISSUE THREAD

**Issue by homanp** [haydenbleasel/roadmap-ui#32]
Hey guys, awesome starting point! 

Are you planing on actively maintaining this?

**Comment by haydenbleasel** [comment]
Hi @homanp, yep it is — I’ve just been heavily focused on another project for the last little while.

Will start digging in to some of the bugs and enhancements in January 👍

**Comment by homanp** [comment]
> Hi @homanp, yep it is — I’ve just been heavily focused on another project for the last little while.
> 
> 
> 
> Will start digging in to some of the bugs and enhancements in January 👍

Great work so far. I will se if I can add some as well.
